// app/layout.tsx
import './globals.css'; // Assuming you have a globals.css file
import { Inter } from 'next/font/google';
import { Providers } from './providers'; // Import the provider we created
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App', // You can change this
  description: 'Generated by create next app', // You can change this
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap the entire app with the Session Provider */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
